project_id = "rfcjhdxsczcwbpknudyy"

[functions.assign-admin-role]
verify_jwt = true

[functions.auto-close-session]
verify_jwt = true

[functions.cleanup-sessions]
verify_jwt = false

[functions.session-summary]
verify_jwt = true

[functions.trial-expiry-check]
verify_jwt = false

[functions.founding-registration]
verify_jwt = false

[functions.founding-scarcity-updater]
verify_jwt = false

[functions.page-tracker]
verify_jwt = false

[functions.analytics-aggregator]
verify_jwt = false

[functions.analytics-processor]
verify_jwt = true