-- Dodanie faz uczenia się dla 10 brakujących umiejętności (50 INSERT statements)

-- Algebra - Działania na liczbach rzeczywistych (skill_id: 1f44da1e-abb1-4c9a-835b-b164d82fe206)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1f44da1e-abb1-4c9a-835b-b164d82fe206', 1, 'Dodawanie i odejmowanie podstawowe', 'Proste działania dodawania i odejmowania bez liczb ujemnych', 'Asystent AI wprowadza temat: proste działania dodawania i odejmowania bez liczb ujemnych. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1f44da1e-abb1-4c9a-835b-b164d82fe206', 2, 'Mnożenie i dzielenie', 'Podstawowe mnożenie i dzielenie z wykorzystaniem małych liczb', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia podstawowe mnożenie i dzielenie z wykorzystaniem małych liczb. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1f44da1e-abb1-4c9a-835b-b164d82fe206', 3, 'Liczby ujemne w działaniach', 'Wprowadzanie i ćwiczenie operacji z liczbami ujemnymi', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wprowadzanie i ćwiczenie operacji z liczbami ujemnymi. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1f44da1e-abb1-4c9a-835b-b164d82fe206', 4, 'Ułamki zwykłe', 'Działania arytmetyczne na ułamkach zwykłych (dodawanie, odejmowanie, mnożenie, dzielenie)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia działania arytmetyczne na ułamkach zwykłych (dodawanie, odejmowanie, mnożenie, dzielenie). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1f44da1e-abb1-4c9a-835b-b164d82fe206', 5, 'Ułamki dziesiętne', 'Działania arytmetyczne na liczbach dziesiętnych (dodawanie, odejmowanie, mnożenie, dzielenie)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia działania arytmetyczne na liczbach dziesiętnych (dodawanie, odejmowanie, mnożenie, dzielenie). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Algebra - Równania kwadratowe (skill_id: f4360fe4-2882-4eaf-8528-d0ea7ecc023f)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'f4360fe4-2882-4eaf-8528-d0ea7ecc023f', 1, 'Podstawy równań kwadratowych', 'Wprowadzenie pojęcia równania kwadratowego i proste przykłady', 'Asystent AI wprowadza temat: wprowadzenie pojęcia równania kwadratowego i proste przykłady. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'f4360fe4-2882-4eaf-8528-d0ea7ecc023f', 2, 'Rozkład na czynniki', 'Rozwiązywanie równań kwadratowych przez rozkład na czynniki', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia rozwiązywanie równań kwadratowych przez rozkład na czynniki. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'f4360fe4-2882-4eaf-8528-d0ea7ecc023f', 3, 'Wzór na pierwiastki', 'Rozwiązywanie równań kwadratowych z wykorzystaniem wzoru na pierwiastki (wzoru kwadratowego)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia rozwiązywanie równań kwadratowych z wykorzystaniem wzoru na pierwiastki (wzoru kwadratowego). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'f4360fe4-2882-4eaf-8528-d0ea7ecc023f', 4, 'Dyskryminant i liczba rozwiązań', 'Analiza równania kwadratowego: obliczanie wyróżnika (Δ) i określanie liczby rozwiązań', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia analizę równania kwadratowego: obliczanie wyróżnika (Δ) i określanie liczby rozwiązań. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'f4360fe4-2882-4eaf-8528-d0ea7ecc023f', 5, 'Zadania tekstowe i zastosowania', 'Zastosowanie równań kwadratowych w zadaniach tekstowych i podsumowanie', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zastosowanie równań kwadratowych w zadaniach tekstowych i podsumowanie. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Algebra - Rozwiązywanie równań liniowych (skill_id: ab3ff5a5-499b-4041-8037-9b76072dced1)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ab3ff5a5-499b-4041-8037-9b76072dced1', 1, 'Jednoetapowe równania', 'Rozwiązywanie prostych równań liniowych wymagających jednego działania', 'Asystent AI wprowadza temat: rozwiązywanie prostych równań liniowych wymagających jednego działania. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ab3ff5a5-499b-4041-8037-9b76072dced1', 2, 'Dwuetapowe równania', 'Rozwiązywanie równań liniowych wymagających dwóch kroków (np. ax + b = c)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia rozwiązywanie równań liniowych wymagających dwóch kroków (np. ax + b = c). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ab3ff5a5-499b-4041-8037-9b76072dced1', 3, 'Równania z niewiadomymi po obu stronach', 'Rozwiązywanie równań liniowych z niewiadomą po obu stronach równania', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia rozwiązywanie równań liniowych z niewiadomą po obu stronach równania. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ab3ff5a5-499b-4041-8037-9b76072dced1', 4, 'Równania z ułamkami i nawiasami', 'Rozwiązywanie równań liniowych zawierających ułamki lub nawiasy', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia rozwiązywanie równań liniowych zawierających ułamki lub nawiasy. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ab3ff5a5-499b-4041-8037-9b76072dced1', 5, 'Zastosowania równań liniowych', 'Wykorzystanie równań liniowych w zadaniach tekstowych i podsumowanie umiejętności', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wykorzystanie równań liniowych w zadaniach tekstowych i podsumowanie umiejętności. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Calculus - Całka nieoznaczona (skill_id: 9f686b42-7f73-49c8-99a1-44fdcad9e17c)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '9f686b42-7f73-49c8-99a1-44fdcad9e17c', 1, 'Pojęcie całki nieoznaczonej', 'Wprowadzenie pojęcia całki nieoznaczonej jako odwrotności pochodnej, stała całkowania, proste przykłady', 'Asystent AI wprowadza temat: wprowadzenie pojęcia całki nieoznaczonej jako odwrotności pochodnej, stała całkowania, proste przykłady. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 12
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '9f686b42-7f73-49c8-99a1-44fdcad9e17c', 2, 'Całkowanie wielomianów', 'Ćwiczenie obliczania całek nieoznaczonych wielomianów (reguła potęgowa i stałe)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia ćwiczenie obliczania całek nieoznaczonych wielomianów (reguła potęgowa i stałe). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '9f686b42-7f73-49c8-99a1-44fdcad9e17c', 3, 'Całki funkcji trygonometrycznych i wykładniczych', 'Obliczanie całek nieoznaczonych podstawowych funkcji trygonometrycznych (sin, cos) oraz wykładniczych (e^x)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia obliczanie całek nieoznaczonych podstawowych funkcji trygonometrycznych (sin, cos) oraz wykładniczych (e^x). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '9f686b42-7f73-49c8-99a1-44fdcad9e17c', 4, 'Metoda podstawiania', 'Wprowadzenie i zastosowanie metody podstawiania do obliczania całek nieoznaczonych', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wprowadzenie i zastosowanie metody podstawiania do obliczania całek nieoznaczonych. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '9f686b42-7f73-49c8-99a1-44fdcad9e17c', 5, 'Sprawdzenie i zastosowania', 'Podsumowanie: różne typy całek, sprawdzenie wyników przez zróżniczkowanie i proste zastosowania', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia podsumowanie: różne typy całek, sprawdzenie wyników przez zróżniczkowanie i proste zastosowania. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);

-- Calculus - Pochodna funkcji (skill_id: ad44342d-dd96-47d3-9992-a627dc6e9ee9)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ad44342d-dd96-47d3-9992-a627dc6e9ee9', 1, 'Definicja i interpretacja', 'Intuicyjne wprowadzenie pochodnej (zmiana chwilowa, nachylenie stycznej) i podstawowe przykłady', 'Asystent AI wprowadza temat: intuicyjne wprowadzenie pochodnej (zmiana chwilowa, nachylenie stycznej) i podstawowe przykłady. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ad44342d-dd96-47d3-9992-a627dc6e9ee9', 2, 'Podstawowe zasady różniczkowania', 'Reguły: pochodna stałej, potęgowa (x^n), mnożenie przez stałą, suma i różnica; ćwiczenie na wielomianach', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia reguły: pochodna stałej, potęgowa (x^n), mnożenie przez stałą, suma i różnica; ćwiczenie na wielomianach. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ad44342d-dd96-47d3-9992-a627dc6e9ee9', 3, 'Iloczyn, iloraz i pochodne funkcji elementarnych', 'Wprowadzenie reguły iloczynowej i ilorazowej; pochodne funkcji takich jak sin x, e^x', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wprowadzenie reguły iloczynowej i ilorazowej; pochodne funkcji takich jak sin x, e^x. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ad44342d-dd96-47d3-9992-a627dc6e9ee9', 4, 'Reguła łańcuchowa', 'Pochodne funkcji złożonych (reguła łańcuchowa); ćwiczenia na złożonych wyrażeniach (np. sin(ax+b))', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia pochodne funkcji złożonych (reguła łańcuchowa); ćwiczenia na złożonych wyrażeniach (np. sin(ax+b)). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'ad44342d-dd96-47d3-9992-a627dc6e9ee9', 5, 'Zastosowania pochodnej', 'Zastosowanie pochodnej: styczne do wykresów, ekstrema; podsumowanie i sprawdzenie opanowania', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zastosowanie pochodnej: styczne do wykresów, ekstrema; podsumowanie i sprawdzenie opanowania. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Functions - Funkcja liniowa (skill_id: 1d4bcd6b-2306-412b-ac3e-600689d473d4)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1d4bcd6b-2306-412b-ac3e-600689d473d4', 1, 'Definicja funkcji liniowej', 'Czym jest funkcja liniowa (y = ax + b), pojęcie argumentu i wartości funkcji, proste przykłady', 'Asystent AI wprowadza temat: czym jest funkcja liniowa (y = ax + b), pojęcie argumentu i wartości funkcji, proste przykłady. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1d4bcd6b-2306-412b-ac3e-600689d473d4', 2, 'Współczynnik kierunkowy i wyraz wolny', 'Interpretacja parametru a (nachylenie prostej) i b (punkt przecięcia z osią Y); wpływ na wykres', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia interpretację parametru a (nachylenie prostej) i b (punkt przecięcia z osią Y); wpływ na wykres. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1d4bcd6b-2306-412b-ac3e-600689d473d4', 3, 'Rysowanie wykresu', 'Metody wykreślania funkcji liniowej: wykorzystanie punktów (np. przecięcia z osiami) i proste przykłady odczytywania wykresu', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia metody wykreślania funkcji liniowej: wykorzystanie punktów (np. przecięcia z osiami) i proste przykłady odczytywania wykresu. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1d4bcd6b-2306-412b-ac3e-600689d473d4', 4, 'Równanie prostej na podstawie danych', 'Wyznaczanie wzoru funkcji liniowej na podstawie danych: dwóch punktów, punktu i nachylenia itp.', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wyznaczanie wzoru funkcji liniowej na podstawie danych: dwóch punktów, punktu i nachylenia itp. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '1d4bcd6b-2306-412b-ac3e-600689d473d4', 5, 'Zastosowania funkcji liniowej', 'Zadania tekstowe wykorzystujące funkcje liniowe (np. zależności proporcjonalne) i podsumowanie', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zadania tekstowe wykorzystujące funkcje liniowe (np. zależności proporcjonalne) i podsumowanie. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Geometry - Twierdzenie Pitagorasa (skill_id: d8d22ed7-67a9-48a9-a0f9-a89aa8f9633f)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'd8d22ed7-67a9-48a9-a0f9-a89aa8f9633f', 1, 'Wprowadzenie do twierdzenia', 'Przedstawienie twierdzenia Pitagorasa na prostych przykładach; sprawdzanie czy trójkąt jest prostokątny', 'Asystent AI wprowadza temat: przedstawienie twierdzenia Pitagorasa na prostych przykładach; sprawdzanie czy trójkąt jest prostokątny. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'd8d22ed7-67a9-48a9-a0f9-a89aa8f9633f', 2, 'Obliczanie przeciwprostokątnej', 'Zastosowanie twierdzenia Pitagorasa do obliczania długości przeciwprostokątnej trójkąta prostokątnego', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zastosowanie twierdzenia Pitagorasa do obliczania długości przeciwprostokątnej trójkąta prostokątnego. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 12
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'd8d22ed7-67a9-48a9-a0f9-a89aa8f9633f', 3, 'Obliczanie przyprostokątnej', 'Zastosowanie twierdzenia Pitagorasa do obliczania brakującej przyprostokątnej', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zastosowanie twierdzenia Pitagorasa do obliczania brakującej przyprostokątnej. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'd8d22ed7-67a9-48a9-a0f9-a89aa8f9633f', 4, 'Zadania praktyczne', 'Zadania tekstowe wykorzystujące twierdzenie Pitagorasa (drabiny, odległości, przekątne itp.)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zadania tekstowe wykorzystujące twierdzenie Pitagorasa (drabiny, odległości, przekątne itp.). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'd8d22ed7-67a9-48a9-a0f9-a89aa8f9633f', 5, 'Sprawdzenie i podsumowanie', 'Podsumowanie umiejętności: różne zadania z twierdzeniem Pitagorasa sprawdzające opanowanie', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia podsumowanie umiejętności: różne zadania z twierdzeniem Pitagorasa sprawdzające opanowanie. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Sequences - Ciągi arytmetyczne (skill_id: 5cdf12f1-c126-464d-b24c-f2f27936f1d8)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '5cdf12f1-c126-464d-b24c-f2f27936f1d8', 1, 'Definicja ciągu arytmetycznego', 'Wprowadzenie pojęcia ciągu arytmetycznego i stałej różnicy pomiędzy wyrazami; rozpoznawanie ciągów arytmetycznych', 'Asystent AI wprowadza temat: wprowadzenie pojęcia ciągu arytmetycznego i stałej różnicy pomiędzy wyrazami; rozpoznawanie ciągów arytmetycznych. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '5cdf12f1-c126-464d-b24c-f2f27936f1d8', 2, 'n-ty wyraz ciągu', 'Wzór ogólny na n-ty wyraz ciągu arytmetycznego; obliczanie dowolnego wyrazu na podstawie wzoru', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wzór ogólny na n-ty wyraz ciągu arytmetycznego; obliczanie dowolnego wyrazu na podstawie wzoru. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '5cdf12f1-c126-464d-b24c-f2f27936f1d8', 3, 'Suma ciągu arytmetycznego', 'Wzór na sumę pierwszych n wyrazów; obliczenia sum i znajdowanie liczby wyrazów na podstawie sumy', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wzór na sumę pierwszych n wyrazów; obliczenia sum i znajdowanie liczby wyrazów na podstawie sumy. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '5cdf12f1-c126-464d-b24c-f2f27936f1d8', 4, 'Zadania z ciągami', 'Zastosowania ciągów arytmetycznych w zadaniach: problemy z codziennym kontekstem i nietypowe pytania', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zastosowania ciągów arytmetycznych w zadaniach: problemy z codziennym kontekstem i nietypowe pytania. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '5cdf12f1-c126-464d-b24c-f2f27936f1d8', 5, 'Podsumowanie i test', 'Różnorodne zadania sprawdzające opanowanie ciągów arytmetycznych', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia różnorodne zadania sprawdzające opanowanie ciągów arytmetycznych. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Statistics - Prawdopodobieństwo klasyczne (skill_id: cbf40a96-b11c-420b-a9c3-174b3c539890)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'cbf40a96-b11c-420b-a9c3-174b3c539890', 1, 'Podstawy prawdopodobieństwa', 'Definicja klasyczna prawdopodobieństwa, przestrzeń zdarzeń i zdarzenie; proste eksperymenty losowe', 'Asystent AI wprowadza temat: definicja klasyczna prawdopodobieństwa, przestrzeń zdarzeń i zdarzenie; proste eksperymenty losowe. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'cbf40a96-b11c-420b-a9c3-174b3c539890', 2, 'Zdarzenia elementarne', 'Obliczanie prawdopodobieństwa prostych zdarzeń w losowych eksperymentach (kostka, moneta itp.)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia obliczanie prawdopodobieństwa prostych zdarzeń w losowych eksperymentach (kostka, moneta itp.). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 12
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'cbf40a96-b11c-420b-a9c3-174b3c539890', 3, 'Zdarzenia niezależne', 'Obliczanie prawdopodobieństwa współwystąpienia niezależnych zdarzeń (zasada mnożenia)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia obliczanie prawdopodobieństwa współwystąpienia niezależnych zdarzeń (zasada mnożenia). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'cbf40a96-b11c-420b-a9c3-174b3c539890', 4, 'Dopełnienie i zdarzenia złożone', 'Wykorzystanie reguły dodawania (dla zdarzeń rozłącznych) i dopełnienia do obliczania prawdopodobieństw złożonych zdarzeń', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wykorzystanie reguły dodawania (dla zdarzeń rozłącznych) i dopełnienia do obliczania prawdopodobieństw złożonych zdarzeń. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    'cbf40a96-b11c-420b-a9c3-174b3c539890', 5, 'Podsumowanie i zastosowania', 'Złożone zadania i problemy z prawdopodobieństwa sprawdzające zrozumienie klasycznej definicji', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia złożone zadania i problemy z prawdopodobieństwa sprawdzające zrozumienie klasycznej definicji. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);

-- Trigonometry - Funkcje trygonometryczne (skill_id: 804945d3-54b9-4944-94b6-4148bec88735)
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '804945d3-54b9-4944-94b6-4148bec88735', 1, 'Wprowadzenie do trygonometrii', 'Definicje sinus, cosinus (i tangens) w trójkącie prostokątnym; jednostki miary kąta (stopnie)', 'Asystent AI wprowadza temat: definicje sinus, cosinus (i tangens) w trójkącie prostokątnym; jednostki miary kąta (stopnie). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 5, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '804945d3-54b9-4944-94b6-4148bec88735', 2, 'Obliczenia w trójkącie prostokątnym', 'Stosowanie funkcji trygonometrycznych do obliczania brakujących długości boków lub miar kątów w trójkącie prostokątnym', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia stosowanie funkcji trygonometrycznych do obliczania brakujących długości boków lub miar kątów w trójkącie prostokątnym. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 8, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 12
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '804945d3-54b9-4944-94b6-4148bec88735', 3, 'Wartości szczególne', 'Wartości funkcji trygonometrycznych dla kątów szczególnych (30°, 45°, 60°) i korzystanie z nich w obliczeniach', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wartości funkcji trygonometrycznych dla kątów szczególnych (30°, 45°, 60°) i korzystanie z nich w obliczeniach. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 4, "min_consecutive_correct": 3, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '804945d3-54b9-4944-94b6-4148bec88735', 4, 'Wykresy i okresowość', 'Wprowadzenie wykresów funkcji sin(x) i cos(x); okresowość, amplituda, przesunięcia fazowe (podstawowe informacje)', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia wprowadzenie wykresów funkcji sin(x) i cos(x); okresowość, amplituda, przesunięcia fazowe (podstawowe informacje). Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Asystent na bieżąco sprawdza postępy ucznia. Gdy uczeń spełnia kryteria sukcesu dla tej fazy, przechodzi do kolejnej fazy. Jeśli uczeń nie spełnia kryteriów, asystent zapewnia dodatkowe ćwiczenia i wsparcie przed przejściem dalej.', '{"min_correct_answers": 10, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 15
);
INSERT INTO skill_phases (skill_id, phase_number, phase_name, phase_description, ai_instructions, success_criteria, estimated_duration_minutes) VALUES (
    '804945d3-54b9-4944-94b6-4148bec88735', 5, 'Zastosowania trygonometrii', 'Zadania praktyczne z zastosowaniem trygonometrii (np. wysokość obiektów, odległości) i podsumowanie wiedzy', 'Asystent AI rozpoczyna fazę krótkim podsumowaniem poprzednich etapów i następnie przedstawia zadania praktyczne z zastosowaniem trygonometrii (np. wysokość obiektów, odległości) i podsumowanie wiedzy. Przedstawia zestaw zadań do rozwiązania i monitoruje odpowiedzi ucznia. Po każdych 2-3 poprawnych odpowiedziach asystent podnosi poziom trudności zadań. Jeśli uczeń popełnia błędy, asystent udziela wskazówek i w razie potrzeby wraca do prostszych przykładów. W trakcie rozwiązywania zadań asystent zadaje pytania kontrolne, aby upewnić się, że uczeń rozumie materiał (np. poproszenie o wyjaśnienie zastosowanej metody). Jeżeli uczeń szybko i bezbłędnie rozwiązuje kolejne zadania, tutor może pominąć najłatwiejsze ćwiczenia i przyspieszyć przejście do trudniejszych przykładów. Po ukończeniu zadań tej fazy asystent ocenia, czy uczeń opanował całość materiału. Jeśli kryteria sukcesu są spełnione, asystent gratuluje i proponuje zakończenie: "Świetnie! Opanowałeś ten materiał. Chcesz kontynuować z kolejnymi przykładami czy przejść do następnego tematu?" W przypadku trudności, oferuje dodatkowe wyjaśnienia lub ćwiczenia utrwalające.', '{"min_correct_answers": 12, "max_errors_allowed": 3, "min_consecutive_correct": 4, "adaptive_difficulty": true, "checkpoint_after_phase": true}', 10
);