-- Add chapter_tag column to skills table if it doesn't exist
ALTER TABLE skills ADD COLUMN IF NOT EXISTS chapter_tag TEXT;

-- Insert all skills data from batches 1 and 2
INSERT INTO skills (
  name, department, level, class_level, men_code, description, chapter_tag, 
  prerequisites, estimated_time_minutes, difficulty_rating, learning_objectives
) VALUES 
-- Batch 1, Part 1 (grades 9-10, algebra)
('Zastosowanie wzoru na kwadrat sumy i różnicy', 'algebra', 'basic', 9, 'III.2.1', 'Stosowanie wzoru skróconego mnożenia (a ± b)^2 do szybkiego rozwijania i upraszczania wyrażeń algebraicznych.', 'Wyrażenia algebraiczne', '["Mnożenie wielomianów (dwumian przez dwumian)"]', 20, 2, '["Uczeń stosuje wzór (a ± b)^2 = a^2 ± 2ab + b^2 do rozwijania sumy i różnicy do kwadratu.", "Uczeń upraszcza wyrażenia algebraiczne, korzystając z powyższego wzoru skróconego mnożenia."]'),

('Różnica kwadratów - rozkład na czynniki', 'algebra', 'basic', 9, 'III.2.1', 'Rozpoznawanie i stosowanie tożsamości a^2 - b^2 = (a - b)(a + b) w celu faktoryzacji wyrażeń algebraicznych.', 'Wyrażenia algebraiczne', '["Zastosowanie wzoru na kwadrat sumy i różnicy"]', 20, 2, '["Uczeń rozkłada wyrażenia w postaci różnicy dwóch kwadratów na iloczyn dwóch czynników liniowych.", "Uczeń rozpoznaje strukturę a^2 - b^2 w wyrażeniu i zastępuje ją iloczynem (a - b)(a + b)."]'),

('Mnożenie wielomianów (dwumian przez dwumian)', 'algebra', 'basic', 9, 'III.2.4', 'Umiejętność mnożenia dwóch dwumianów (lub ogólnie wielomianów) z wykorzystaniem rozdzielności mnożenia względem dodawania.', 'Wyrażenia algebraiczne', '[]', 20, 2, '["Uczeń mnoży dwa dwumiany, np. (ax + b)(cx + d), obliczając sumę iloczynów wszystkich par składników.", "Uczeń porządkuje i upraszcza otrzymany wielomian po wykonaniu mnożenia."]'),

('Wyłączanie wspólnego czynnika przed nawias', 'algebra', 'basic', 9, 'III.2.3', 'Faktoryzacja wyrażenia algebraicznego poprzez wyciągnięcie największego wspólnego czynnika przed nawias w celu uproszczenia wyrażenia.', 'Wyrażenia algebraiczne', '["Mnożenie wielomianów (dwumian przez dwumian)"]', 20, 2, '["Uczeń identyfikuje największy wspólny dzielnik jednomianowy wyrazów wielomianu.", "Uczeń wyłącza wspólny czynnik przed nawias i zapisuje wyrażenie w postaci iloczynu tego czynnika oraz pozostałego wielomianu."]'),

('Grupowanie wyrazów przy rozkładaniu wielomianu', 'algebra', 'advanced', 10, 'III.2.3', 'Zaawansowana technika faktoryzacji wielomianów polegająca na grupowaniu wyrazów w pary w celu znalezienia wspólnych czynników i rozłożenia wielomianu na iloczyny.', 'Wyrażenia algebraiczne', '["Wyłączanie wspólnego czynnika przed nawias", "Mnożenie wielomianów (dwumian przez dwumian)"]', 25, 4, '["Uczeń rozkłada wielomian na grupy wyrazów w taki sposób, aby w każdej grupie można było wyłączyć wspólny czynnik.", "Uczeń stosuje dwukrotnie wyłączanie czynnika: najpierw w każdej z grup, a następnie na wyrażeniu powstałym po pogrupowaniu, uzyskując iloczyn dwóch wielomianów."]'),

-- Batch 1, Part 2 (grades 9-10, algebra/functions continued)
('Rozwiązywanie równań kwadratowych metodą faktoryzacji', 'algebra', 'basic', 9, 'III.2.5', 'Uczeń rozwiązuje równania kwadratowe poprzez rozkład trójmianu na czynniki i zastosowanie prawa iloczynu zerowego.', 'Równania kwadratowe', '["Różnica kwadratów - rozkład na czynniki", "Wyłączanie wspólnego czynnika przed nawias"]', 25, 3, '["Uczeń rozpoznaje możliwość rozkładu trójmianu kwadratowego na iloczyn czynników liniowych.", "Uczeń stosuje prawo iloczynu zerowego do znajdowania rozwiązań równania."]'),

('Rozwiązywanie równań kwadratowych za pomocą wzorów Viète''a', 'algebra', 'intermediate', 9, 'III.2.6', 'Uczeń znajduje pierwiastki równania kwadratowego korzystając z zależności Viète''a między współczynnikami a pierwiastkami.', 'Równania kwadratowe', '["Rozwiązywanie równań kwadratowych metodą faktoryzacji"]', 25, 3, '["Uczeń rozpoznaje równanie kwadratowe w postaci kanonicznej.", "Uczeń stosuje wzory Viète''a do obliczania sumy i iloczynu pierwiastków.", "Uczeń potrafi wyznaczyć pierwiastki równania na podstawie zależności Viète''a."]'),

('Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ', 'functions', 'basic', 9, 'III.3.2', 'Uczeń oblicza miejsca zerowe funkcji kwadratowej, korzystając z wyróżnika trójmianu kwadratowego.', 'Funkcje kwadratowe', '["Rozwiązywanie równań kwadratowych metodą faktoryzacji"]', 30, 3, '["Uczeń oblicza wartość wyróżnika Δ = b^2 - 4ac.", "Uczeń określa liczbę miejsc zerowych funkcji na podstawie wartości Δ.", "Uczeń wyznacza pierwiastki równania kwadratowego przy pomocy wzoru kwadratowego."]'),

('Wyznaczanie wierzchołka paraboli', 'functions', 'intermediate', 10, 'III.3.3', 'Uczeń znajduje współrzędne wierzchołka paraboli funkcji kwadratowej w postaci ogólnej y = ax^2 + bx + c.', 'Funkcje kwadratowe', '["Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ"]', 25, 3, '["Uczeń korzysta ze wzoru na współrzędne wierzchołka: x0 = -b / 2a, y0 = -Δ / 4a.", "Uczeń oblicza i interpretuje położenie wierzchołka paraboli na płaszczyźnie."]'),

('Szkicowanie wykresu funkcji kwadratowej', 'functions', 'intermediate', 10, 'III.3.3', 'Uczeń potrafi naszkicować wykres paraboli, korzystając z miejsc zerowych, wierzchołka oraz współczynnika kierunkowego a.', 'Funkcje kwadratowe', '["Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ", "Wyznaczanie wierzchołka paraboli"]', 30, 4, '["Uczeń rozpoznaje kształt paraboli w zależności od znaku współczynnika a.", "Uczeń wyznacza kluczowe punkty wykresu: miejsca zerowe, wierzchołek, punkt przecięcia z osią OY.", "Uczeń szkicuje wykres paraboli na układzie współrzędnych."]'),

-- Batch 1, Part 3 (grades 9-10, analytic geometry)
('Równanie prostej w postaci kierunkowej', 'geometry', 'basic', 9, 'III.4.1', 'Uczeń zapisuje równanie prostej w układzie współrzędnych w postaci y = ax + b na podstawie współczynnika kierunkowego i punktu.', 'Geometria analityczna', '["Podstawy układu współrzędnych"]', 20, 2, '["Uczeń wyznacza współczynnik kierunkowy prostej przechodzącej przez dwa punkty.", "Uczeń zapisuje równanie prostej w postaci y = ax + b.", "Uczeń interpretuje współczynnik kierunkowy jako tangens kąta nachylenia prostej do osi OX."]'),

('Równanie prostej w postaci ogólnej', 'geometry', 'intermediate', 9, 'III.4.1', 'Uczeń zapisuje równanie prostej w postaci Ax + By + C = 0 oraz przekształca je do postaci kierunkowej i odwrotnie.', 'Geometria analityczna', '["Równanie prostej w postaci kierunkowej"]', 20, 3, '["Uczeń zna i stosuje równanie prostej w postaci ogólnej Ax + By + C = 0.", "Uczeń przekształca równanie z postaci ogólnej do kierunkowej i odwrotnie.", "Uczeń rozpoznaje proste równoległe i prostopadłe na podstawie równań."]'),

('Odległość punktu od prostej', 'geometry', 'intermediate', 10, 'III.4.2', 'Uczeń oblicza odległość punktu od prostej w układzie współrzędnych, korzystając ze wzoru analitycznego.', 'Geometria analityczna', '["Równanie prostej w postaci ogólnej"]', 25, 3, '["Uczeń zna wzór na odległość punktu P(x0,y0) od prostej Ax+By+C=0: d = |Ax0+By0+C| / √(A^2+B^2).", "Uczeń stosuje wzór do obliczania odległości punktu od danej prostej.", "Uczeń interpretuje geometrycznie otrzymany wynik."]'),

('Równanie okręgu w układzie współrzędnych', 'geometry', 'basic', 9, 'III.4.3', 'Uczeń zapisuje równanie okręgu o środku w punkcie (a, b) i promieniu r w postaci (x - a)^2 + (y - b)^2 = r^2.', 'Geometria analityczna', '["Podstawy układu współrzędnych"]', 20, 2, '["Uczeń zna wzór na równanie okręgu o danym środku i promieniu.", "Uczeń rozpoznaje równanie okręgu i potrafi wskazać jego środek i promień.", "Uczeń rysuje okrąg w układzie współrzędnych na podstawie równania."]'),

('Wektory - dodawanie i odejmowanie', 'geometry', 'basic', 9, 'III.4.4', 'Uczeń wykonuje działania na wektorach w układzie współrzędnych: dodawanie, odejmowanie, mnożenie przez liczbę.', 'Geometria analityczna - wektory', '["Podstawy układu współrzędnych"]', 20, 2, '["Uczeń dodaje i odejmuje wektory, stosując regułę równoległoboku i/lub rachunek współrzędnych.", "Uczeń mnoży wektor przez liczbę i interpretuje wynik geometrycznie.", "Uczeń stosuje działania na wektorach w prostych zadaniach geometrycznych."]'),

('Iloczyn skalarny wektorów', 'geometry', 'intermediate', 10, 'III.4.4', 'Uczeń oblicza iloczyn skalarny wektorów i interpretuje go geometrycznie jako miarę kąta między wektorami.', 'Geometria analityczna - wektory', '["Wektory - dodawanie i odejmowanie"]', 25, 3, '["Uczeń zna wzór na iloczyn skalarny: u·v = |u||v|cosα oraz u·v = x1x2 + y1y2.", "Uczeń oblicza iloczyn skalarny wektorów w zadaniach liczbowych.", "Uczeń wykorzystuje iloczyn skalarny do wyznaczania kąta między wektorami i sprawdzania prostopadłości."]'),

-- Batch 1, Part 4 (grades 9-10, systems of equations and advanced functions)
('Układy równań liniowych metodą podstawiania', 'algebra', 'basic', 9, 'III.2.7', 'Uczeń rozwiązuje układy dwóch równań liniowych z dwiema niewiadomymi metodą podstawiania.', 'Układy równań', '["Rozwiązywanie równań liniowych z jedną niewiadomą"]', 25, 3, '["Uczeń przekształca jedno z równań, aby wyrazić jedną niewiadomą przez drugą.", "Uczeń podstawia wyrażenie do drugiego równania i oblicza rozwiązanie.", "Uczeń sprawdza poprawność rozwiązania poprzez podstawienie do obu równań."]'),

('Układy równań liniowych metodą przeciwnych współczynników', 'algebra', 'basic', 9, 'III.2.7', 'Uczeń rozwiązuje układy dwóch równań liniowych metodą przeciwnych współczynników (dodawania/odejmowania równań).', 'Układy równań', '["Układy równań liniowych metodą podstawiania"]', 25, 3, '["Uczeń mnoży równania układu przez odpowiednie liczby, aby uzyskać przeciwne współczynniki.", "Uczeń dodaje/odejmuje równania i oblicza niewiadome.", "Uczeń zapisuje rozwiązanie układu w postaci uporządkowanej pary liczb."]'),

('Zastosowanie układów równań w zadaniach tekstowych', 'algebra', 'intermediate', 10, 'III.2.7', 'Uczeń modeluje sytuacje praktyczne za pomocą układów równań i rozwiązuje je.', 'Układy równań', '["Układy równań liniowych metodą przeciwnych współczynników"]', 30, 4, '["Uczeń tłumaczy zadanie tekstowe na język równań liniowych.", "Uczeń rozwiązuje układ i interpretuje wynik w kontekście problemu.", "Uczeń analizuje poprawność modelu matematycznego."]'),

('Badanie monotoniczności funkcji liniowej', 'functions', 'basic', 9, 'III.3.1', 'Uczeń bada monotoniczność funkcji liniowej w zależności od współczynnika kierunkowego a.', 'Funkcja liniowa', '["Równanie prostej w postaci kierunkowej"]', 20, 2, '["Uczeń interpretuje współczynnik kierunkowy jako wskaźnik rosnącego lub malejącego charakteru funkcji.", "Uczeń rozpoznaje, że a > 0 oznacza funkcję rosnącą, a < 0 – malejącą."]'),

('Obliczanie wartości funkcji liniowej', 'functions', 'basic', 9, 'III.3.1', 'Uczeń oblicza wartość funkcji liniowej dla danego argumentu.', 'Funkcja liniowa', '["Badanie monotoniczności funkcji liniowej"]', 15, 1, '["Uczeń podstawia wartość x do wzoru funkcji y = ax + b i oblicza y.", "Uczeń interpretuje wynik w kontekście problemu tekstowego."]'),

('Równoległość i prostopadłość prostych w układzie współrzędnych', 'geometry', 'intermediate', 10, 'III.4.1', 'Uczeń bada warunki równoległości i prostopadłości prostych na podstawie współczynników kierunkowych.', 'Geometria analityczna', '["Równanie prostej w postaci ogólnej"]', 25, 3, '["Uczeń rozpoznaje równoległość prostych, gdy mają równe współczynniki kierunkowe.", "Uczeń rozpoznaje prostopadłość prostych, gdy iloczyn współczynników kierunkowych wynosi -1.", "Uczeń interpretuje geometrycznie zależności między prostymi."]'),

-- Batch 1, Part 5 (grades 9-10, advanced quadratic functions and vectors)
('Przekształcanie wzoru funkcji kwadratowej do postaci kanonicznej', 'functions', 'intermediate', 10, 'III.3.3', 'Uczeń przekształca wzór funkcji kwadratowej y = ax^2 + bx + c do postaci kanonicznej y = a(x - p)^2 + q poprzez dopełnianie kwadratu.', 'Funkcje kwadratowe', '["Wyznaczanie wierzchołka paraboli"]', 30, 4, '["Uczeń stosuje metodę dopełniania kwadratu do przekształcania postaci ogólnej funkcji kwadratowej.", "Uczeń interpretuje parametry p i q jako współrzędne wierzchołka paraboli."]'),

('Analiza znaku funkcji kwadratowej', 'functions', 'advanced', 10, 'III.3.3', 'Uczeń bada przedziały, w których funkcja kwadratowa przyjmuje wartości dodatnie i ujemne.', 'Funkcje kwadratowe', '["Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ"]', 25, 4, '["Uczeń zaznacza miejsca zerowe na osi liczbowej.", "Uczeń określa znak funkcji w poszczególnych przedziałach między miejscami zerowymi.", "Uczeń interpretuje znak funkcji kwadratowej w kontekście wykresu paraboli."]'),

('Zadania tekstowe z funkcją kwadratową', 'functions', 'advanced', 10, 'III.3.4', 'Uczeń rozwiązuje zadania praktyczne, w których model matematyczny stanowi funkcja kwadratowa (np. optymalizacja pola, ceny, prędkości).', 'Funkcje kwadratowe - zastosowania', '["Szkicowanie wykresu funkcji kwadratowej", "Analiza znaku funkcji kwadratowej"]', 35, 5, '["Uczeń buduje model funkcją kwadratową dla sytuacji opisanej w zadaniu.", "Uczeń znajduje wartości optymalne (maksimum/minimum) i interpretuje je kontekstowo.", "Uczeń rozwiązuje zadania problemowe z zastosowaniem funkcji kwadratowej."]'),

('Zastosowanie wektorów do obliczania pól figur', 'geometry', 'advanced', 10, 'III.4.5', 'Uczeń oblicza pola trójkątów i równoległoboków korzystając z własności wektorów i iloczynu wektorowego w R².', 'Geometria analityczna - wektory', '["Iloczyn skalarny wektorów"]', 30, 5, '["Uczeń stosuje wzór na pole trójkąta w oparciu o wektory.", "Uczeń oblicza pole równoległoboku jako wartość iloczynu wektorowego.", "Uczeń interpretuje rozwiązania geometrycznie na układzie współrzędnych."]'),

('Rozwiązywanie układów równań kwadratowych i liniowych', 'algebra', 'advanced', 10, 'III.2.8', 'Uczeń rozwiązuje układy równań, w których jedno równanie jest kwadratowe, a drugie liniowe.', 'Układy równań nieliniowych', '["Rozwiązywanie równań kwadratowych za pomocą wzorów Viète''a", "Układy równań liniowych metodą przeciwnych współczynników"]', 35, 5, '["Uczeń podstawia wyrażenie liniowe do równania kwadratowego.", "Uczeń rozwiązuje otrzymane równanie kwadratowe i interpretuje rozwiązania.", "Uczeń analizuje liczbę i rodzaj rozwiązań geometrycznie (przecięcie paraboli i prostej)."]'),

-- Batch 2, Part 1 (grades 11-12, calculus - derivatives)
('Definicja granicy funkcji w punkcie', 'calculus', 'basic', 11, 'IV.1.1', 'Uczeń rozumie pojęcie granicy funkcji w punkcie i potrafi zapisać je w notacji ε-δ w prostych przypadkach.', 'Granice funkcji', '["Granice ciągów"]', 25, 3, '["Uczeń rozpoznaje, czym jest granica funkcji w punkcie.", "Uczeń stosuje prostą notację granicy lim_{x→a} f(x).", "Uczeń interpretuje granicę graficznie na wykresie funkcji."]'),

('Granica jednostronna funkcji', 'calculus', 'basic', 11, 'IV.1.2', 'Uczeń oblicza granice jednostronne funkcji w prostych przypadkach, np. funkcji wymiernych.', 'Granice funkcji', '["Definicja granicy funkcji w punkcie"]', 25, 3, '["Uczeń rozumie różnicę między granicą prawostronną a lewostronną.", "Uczeń potrafi obliczyć granice jednostronne dla funkcji prostych.", "Uczeń interpretuje sytuacje, w których granice jednostronne są różne."]'),

('Granica w nieskończoności', 'calculus', 'basic', 11, 'IV.1.3', 'Uczeń oblicza granice funkcji przy x dążącym do +∞ lub -∞.', 'Granice funkcji', '["Granica jednostronna funkcji"]', 20, 3, '["Uczeń oblicza granice funkcji wymiernych przy x→±∞.", "Uczeń interpretuje granicę w nieskończoności jako asymptotę poziomą.", "Uczeń rozpoznaje przypadki, gdy granica nie istnieje."]'),

('Definicja pochodnej w punkcie', 'calculus', 'intermediate', 11, 'IV.2.1', 'Uczeń definiuje pochodną funkcji w punkcie jako granicę ilorazu różnicowego.', 'Pochodne - definicja', '["Definicja granicy funkcji w punkcie"]', 30, 4, '["Uczeń zna definicję pochodnej: f''(x0) = lim_{h→0} (f(x0+h)-f(x0))/h.", "Uczeń interpretuje pochodną jako współczynnik kierunkowy stycznej.", "Uczeń rozpoznaje geometryczne znaczenie pochodnej."]'),

('Podstawowe reguły różniczkowania', 'calculus', 'intermediate', 11, 'IV.2.2', 'Uczeń stosuje reguły różniczkowania sumy, różnicy, iloczynu i ilorazu funkcji elementarnych.', 'Pochodne - reguły', '["Definicja pochodnej w punkcie"]', 30, 4, '["Uczeń różniczkuje wielomiany, funkcje wymierne i proste funkcje trygonometryczne.", "Uczeń stosuje regułę iloczynu i ilorazu w prostych przykładach.", "Uczeń potrafi wyprowadzić wzory na pochodne funkcji potęgowych."]'),

('Zastosowanie pochodnych do badania monotoniczności', 'calculus', 'intermediate', 11, 'IV.2.3', 'Uczeń wykorzystuje znak pochodnej do badania przedziałów monotoniczności funkcji.', 'Pochodne - zastosowania', '["Podstawowe reguły różniczkowania"]', 30, 4, '["Uczeń bada przedziały, w których funkcja rośnie lub maleje.", "Uczeń stosuje badanie monotoniczności do szkicowania wykresów.", "Uczeń interpretuje monotoniczność funkcji w zadaniach praktycznych."]'),

('Ekstrema lokalne funkcji', 'calculus', 'advanced', 12, 'IV.2.4', 'Uczeń wykorzystuje pochodną pierwszego i drugiego rzędu do znajdowania ekstremów lokalnych funkcji.', 'Pochodne - ekstrema', '["Zastosowanie pochodnych do badania monotoniczności"]', 35, 5, '["Uczeń oblicza punkty krytyczne funkcji.", "Uczeń stosuje test pierwszej i drugiej pochodnej do rozróżniania minimów i maksimów.", "Uczeń interpretuje ekstremum w zadaniach optymalizacyjnych."]'),

-- Batch 2, Part 2 (grades 11-12, calculus - integrals and trigonometry)
('Całka nieoznaczona funkcji potęgowej', 'calculus', 'basic', 11, 'IV.3.1', 'Uczeń oblicza całki nieoznaczone funkcji postaci x^n, gdzie n ≠ -1.', 'Całki - podstawy', '["Podstawowe reguły różniczkowania"]', 25, 3, '["Uczeń zna wzór ∫ x^n dx = x^(n+1)/(n+1) + C dla n ≠ -1.", "Uczeń stosuje wzór w zadaniach obliczeniowych.", "Uczeń interpretuje wynik jako rodzinę funkcji różniących się stałą C."]'),

('Całka nieoznaczona funkcji wymiernych', 'calculus', 'intermediate', 11, 'IV.3.2', 'Uczeń oblicza całki nieoznaczone funkcji wymiernych przy użyciu prostych podstawień.', 'Całki - techniki podstawowe', '["Całka nieoznaczona funkcji potęgowej"]', 30, 4, '["Uczeń wykonuje podstawienie zmiennej w prostych przypadkach.", "Uczeń oblicza całki wymierne poprzez redukcję do całek potęgowych.", "Uczeń rozpoznaje kiedy zastosować odpowiednie podstawienie."]'),

('Całka oznaczona jako pole pod wykresem funkcji', 'calculus', 'intermediate', 11, 'IV.3.3', 'Uczeń interpretuje całkę oznaczoną jako pole obszaru pod wykresem funkcji.', 'Całki - zastosowania geometryczne', '["Całka nieoznaczona funkcji potęgowej"]', 30, 4, '["Uczeń zna definicję całki oznaczonej jako granicy sum Riemanna.", "Uczeń oblicza pole obszaru ograniczonego osią OX i wykresem funkcji.", "Uczeń stosuje całkę oznaczoną do prostych zadań geometrycznych."]'),

('Zastosowanie całek w obliczaniu objętości brył obrotowych', 'calculus', 'advanced', 12, 'IV.3.4', 'Uczeń oblicza objętość bryły obrotowej powstałej przez obrót obszaru wokół osi OX.', 'Całki - zastosowania przestrzenne', '["Całka oznaczona jako pole pod wykresem funkcji"]', 35, 5, '["Uczeń zna wzór V = π∫[a,b] f(x)^2 dx.", "Uczeń stosuje wzór do obliczeń objętości prostych brył obrotowych.", "Uczeń interpretuje wynik geometrycznie."]'),

('Tożsamości trygonometryczne - przekształcanie wyrażeń', 'trigonometry', 'intermediate', 11, 'IV.4.1', 'Uczeń stosuje podstawowe tożsamości trygonometryczne (sin²x + cos²x = 1, 1 + tan²x = sec²x) do upraszczania wyrażeń.', 'Trygonometria - tożsamości', '["Podstawowe funkcje trygonometryczne kąta ostrego"]', 25, 3, '["Uczeń zna i stosuje podstawowe tożsamości trygonometryczne.", "Uczeń upraszcza wyrażenia trygonometryczne w prostych zadaniach.", "Uczeń rozpoznaje równoważność wyrażeń dzięki tożsamościom."]'),

('Rozwiązywanie równań trygonometrycznych', 'trigonometry', 'intermediate', 11, 'IV.4.2', 'Uczeń rozwiązuje proste równania trygonometryczne typu sinx = a, cosx = a, tanx = a.', 'Trygonometria - równania', '["Tożsamości trygonometryczne - przekształcanie wyrażeń"]', 30, 4, '["Uczeń zapisuje rozwiązania równań trygonometrycznych w postaci ogólnej.", "Uczeń znajduje wszystkie rozwiązania równania w danym przedziale.", "Uczeń interpretuje rozwiązania na kole trygonometrycznym."]'),

('Twierdzenie sinusów i cosinusów', 'trigonometry', 'advanced', 11, 'IV.4.3', 'Uczeń stosuje twierdzenie sinusów i cosinusów do rozwiązywania trójkątów dowolnych.', 'Trygonometria - zastosowania', '["Rozwiązywanie równań trygonometrycznych"]', 35, 5, '["Uczeń zna wzory: a/sinα = b/sinβ = c/sinγ oraz c² = a² + b² - 2abcosγ.", "Uczeń stosuje twierdzenia do wyznaczania boków i kątów w trójkątach.", "Uczeń rozwiązuje zadania praktyczne z geometrii płaskiej."]'),

-- Batch 2, Part 3 (grades 11-12, statistics and probability)
('Permutacje bez powtórzeń', 'statistics', 'basic', 11, 'IV.5.1', 'Uczeń oblicza liczbę permutacji n-elementowego zbioru bez powtórzeń.', 'Kombinatoryka', '["Podstawowe działania na silni"]', 20, 3, '["Uczeń zna wzór P(n) = n!.", "Uczeń oblicza liczbę permutacji dla małych wartości n.", "Uczeń interpretuje wynik w prostych zadaniach kombinatorycznych."]'),

('Wariacje i kombinacje', 'statistics', 'intermediate', 11, 'IV.5.2', 'Uczeń oblicza liczbę wariacji i kombinacji bez powtórzeń, stosując odpowiednie wzory.', 'Kombinatoryka', '["Permutacje bez powtórzeń"]', 30, 4, '["Uczeń zna wzory na wariacje V(n,k) i kombinacje C(n,k).", "Uczeń stosuje wzory do prostych zadań obliczeniowych.", "Uczeń rozróżnia sytuacje wymagające użycia permutacji, wariacji lub kombinacji."]'),

('Prawdopodobieństwo klasyczne zdarzenia', 'statistics', 'basic', 11, 'IV.5.3', 'Uczeń oblicza prawdopodobieństwo zdarzeń w modelu klasycznym.', 'Prawdopodobieństwo klasyczne', '["Wariacje i kombinacje"]', 25, 3, '["Uczeń zna wzór P(A) = m/n dla zdarzeń równoprawdopodobnych.", "Uczeń oblicza prawdopodobieństwo prostych zdarzeń w losowaniach.", "Uczeń interpretuje wynik w kontekście zadania."]'),

('Prawdopodobieństwo warunkowe', 'statistics', 'intermediate', 12, 'IV.5.4', 'Uczeń oblicza prawdopodobieństwo warunkowe zdarzenia i zna wzór Bayesa.', 'Prawdopodobieństwo warunkowe', '["Prawdopodobieństwo klasyczne zdarzenia"]', 30, 4, '["Uczeń zna wzór P(A|B) = P(A∩B)/P(B).", "Uczeń oblicza prawdopodobieństwa w zadaniach z zależnymi zdarzeniami.", "Uczeń stosuje wzór Bayesa w prostych przypadkach."]'),

('Rozkłady prawdopodobieństwa - zmienne dyskretne', 'statistics', 'intermediate', 12, 'IV.5.5', 'Uczeń zna podstawowe rozkłady prawdopodobieństwa dla zmiennych losowych dyskretnych (Bernoulliego, dwumianowy).', 'Rozkłady prawdopodobieństwa', '["Prawdopodobieństwo warunkowe"]', 35, 4, '["Uczeń definiuje zmienną losową dyskretną.", "Uczeń zna i stosuje wzór rozkładu dwumianowego.", "Uczeń interpretuje wartości oczekiwane i wariancję."]'),

('Statystyka opisowa - średnia, mediana, moda', 'statistics', 'basic', 11, 'IV.6.1', 'Uczeń oblicza podstawowe miary tendencji centralnej: średnią, medianę i modę.', 'Statystyka opisowa', '["Działania na liczbach rzeczywistych"]', 20, 2, '["Uczeń oblicza średnią arytmetyczną zbioru danych.", "Uczeń znajduje medianę i modę.", "Uczeń interpretuje znaczenie tych miar w kontekście danych statystycznych."]');