-- Add chapter_tag column to skills table if it doesn't exist
ALTER TABLE skills ADD COLUMN IF NOT EXISTS chapter_tag TEXT;

-- Insert all skills data from batches 1 and 2 with proper array formatting
INSERT INTO skills (
  name, department, level, class_level, men_code, description, chapter_tag, 
  prerequisites, estimated_time_minutes, difficulty_rating, learning_objectives
) VALUES 
-- Batch 1, Part 1 (grades 9-10, algebra)
('Zastosowanie wzoru na kwadrat sumy i różnicy', 'algebra', 'basic', 9, 'III.2.1', 'Stosowanie wzoru skróconego mnożenia (a ± b)^2 do szybkiego rozwijania i upraszczania wyrażeń algebraicznych.', 'Wyrażenia algebraiczne', ARRAY['Mnożenie wielomianów (dwumian przez dwumian)'], 20, 2, ARRAY['Uczeń stosuje wzór (a ± b)^2 = a^2 ± 2ab + b^2 do rozwijania sumy i różnicy do kwadratu.', 'Uczeń upraszcza wyrażenia algebraiczne, korzystając z powyższego wzoru skróconego mnożenia.']),

('Różnica kwadratów - rozkład na czynniki', 'algebra', 'basic', 9, 'III.2.1', 'Rozpoznawanie i stosowanie tożsamości a^2 - b^2 = (a - b)(a + b) w celu faktoryzacji wyrażeń algebraicznych.', 'Wyrażenia algebraiczne', ARRAY['Zastosowanie wzoru na kwadrat sumy i różnicy'], 20, 2, ARRAY['Uczeń rozkłada wyrażenia w postaci różnicy dwóch kwadratów na iloczyn dwóch czynników liniowych.', 'Uczeń rozpoznaje strukturę a^2 - b^2 w wyrażeniu i zastępuje ją iloczynem (a - b)(a + b).']),

('Mnożenie wielomianów (dwumian przez dwumian)', 'algebra', 'basic', 9, 'III.2.4', 'Umiejętność mnożenia dwóch dwumianów (lub ogólnie wielomianów) z wykorzystaniem rozdzielności mnożenia względem dodawania.', 'Wyrażenia algebraiczne', ARRAY[]::text[], 20, 2, ARRAY['Uczeń mnoży dwa dwumiany, np. (ax + b)(cx + d), obliczając sumę iloczynów wszystkich par składników.', 'Uczeń porządkuje i upraszcza otrzymany wielomian po wykonaniu mnożenia.']),

('Wyłączanie wspólnego czynnika przed nawias', 'algebra', 'basic', 9, 'III.2.3', 'Faktoryzacja wyrażenia algebraicznego poprzez wyciągnięcie największego wspólnego czynnika przed nawias w celu uproszczenia wyrażenia.', 'Wyrażenia algebraiczne', ARRAY['Mnożenie wielomianów (dwumian przez dwumian)'], 20, 2, ARRAY['Uczeń identyfikuje największy wspólny dzielnik jednomianowy wyrazów wielomianu.', 'Uczeń wyłącza wspólny czynnik przed nawias i zapisuje wyrażenie w postaci iloczynu tego czynnika oraz pozostałego wielomianu.']),

('Grupowanie wyrazów przy rozkładaniu wielomianu', 'algebra', 'advanced', 10, 'III.2.3', 'Zaawansowana technika faktoryzacji wielomianów polegająca na grupowaniu wyrazów w pary w celu znalezienia wspólnych czynników i rozłożenia wielomianu na iloczyny.', 'Wyrażenia algebraiczne', ARRAY['Wyłączanie wspólnego czynnika przed nawias', 'Mnożenie wielomianów (dwumian przez dwumian)'], 25, 4, ARRAY['Uczeń rozkłada wielomian na grupy wyrazów w taki sposób, aby w każdej grupie można było wyłączyć wspólny czynnik.', 'Uczeń stosuje dwukrotnie wyłączanie czynnika: najpierw w każdej z grup, a następnie na wyrażeniu powstałym po pogrupowaniu, uzyskując iloczyn dwóch wielomianów.']),

-- Batch 1, Part 2 (grades 9-10, algebra/functions continued)
('Rozwiązywanie równań kwadratowych metodą faktoryzacji', 'algebra', 'basic', 9, 'III.2.5', 'Uczeń rozwiązuje równania kwadratowe poprzez rozkład trójmianu na czynniki i zastosowanie prawa iloczynu zerowego.', 'Równania kwadratowe', ARRAY['Różnica kwadratów - rozkład na czynniki', 'Wyłączanie wspólnego czynnika przed nawias'], 25, 3, ARRAY['Uczeń rozpoznaje możliwość rozkładu trójmianu kwadratowego na iloczyn czynników liniowych.', 'Uczeń stosuje prawo iloczynu zerowego do znajdowania rozwiązań równania.']),

('Rozwiązywanie równań kwadratowych za pomocą wzorów Viète''a', 'algebra', 'intermediate', 9, 'III.2.6', 'Uczeń znajduje pierwiastki równania kwadratowego korzystając z zależności Viète''a między współczynnikami a pierwiastkami.', 'Równania kwadratowe', ARRAY['Rozwiązywanie równań kwadratowych metodą faktoryzacji'], 25, 3, ARRAY['Uczeń rozpoznaje równanie kwadratowe w postaci kanonicznej.', 'Uczeń stosuje wzory Viète''a do obliczania sumy i iloczynu pierwiastków.', 'Uczeń potrafi wyznaczyć pierwiastki równania na podstawie zależności Viète''a.']),

('Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ', 'functions', 'basic', 9, 'III.3.2', 'Uczeń oblicza miejsca zerowe funkcji kwadratowej, korzystając z wyróżnika trójmianu kwadratowego.', 'Funkcje kwadratowe', ARRAY['Rozwiązywanie równań kwadratowych metodą faktoryzacji'], 30, 3, ARRAY['Uczeń oblicza wartość wyróżnika Δ = b^2 - 4ac.', 'Uczeń określa liczbę miejsc zerowych funkcji na podstawie wartości Δ.', 'Uczeń wyznacza pierwiastki równania kwadratowego przy pomocy wzoru kwadratowego.']),

('Wyznaczanie wierzchołka paraboli', 'functions', 'intermediate', 10, 'III.3.3', 'Uczeń znajduje współrzędne wierzchołka paraboli funkcji kwadratowej w postaci ogólnej y = ax^2 + bx + c.', 'Funkcje kwadratowe', ARRAY['Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ'], 25, 3, ARRAY['Uczeń korzysta ze wzoru na współrzędne wierzchołka: x0 = -b / 2a, y0 = -Δ / 4a.', 'Uczeń oblicza i interpretuje położenie wierzchołka paraboli na płaszczyźnie.']),

('Szkicowanie wykresu funkcji kwadratowej', 'functions', 'intermediate', 10, 'III.3.3', 'Uczeń potrafi naszkicować wykres paraboli, korzystając z miejsc zerowych, wierzchołka oraz współczynnika kierunkowego a.', 'Funkcje kwadratowe', ARRAY['Wyznaczanie miejsc zerowych funkcji kwadratowej metodą wyróżnika Δ', 'Wyznaczanie wierzchołka paraboli'], 30, 4, ARRAY['Uczeń rozpoznaje kształt paraboli w zależności od znaku współczynnika a.', 'Uczeń wyznacza kluczowe punkty wykresu: miejsca zerowe, wierzchołek, punkt przecięcia z osią OY.', 'Uczeń szkicuje wykres paraboli na układzie współrzędnych.']),

-- Continue with remaining skills...
('Równanie prostej w postaci kierunkowej', 'geometry', 'basic', 9, 'III.4.1', 'Uczeń zapisuje równanie prostej w układzie współrzędnych w postaci y = ax + b na podstawie współczynnika kierunkowego i punktu.', 'Geometria analityczna', ARRAY['Podstawy układu współrzędnych'], 20, 2, ARRAY['Uczeń wyznacza współczynnik kierunkowy prostej przechodzącej przez dwa punkty.', 'Uczeń zapisuje równanie prostej w postaci y = ax + b.', 'Uczeń interpretuje współczynnik kierunkowy jako tangens kąta nachylenia prostej do osi OX.']),

('Równanie prostej w postaci ogólnej', 'geometry', 'intermediate', 9, 'III.4.1', 'Uczeń zapisuje równanie prostej w postaci Ax + By + C = 0 oraz przekształca je do postaci kierunkowej i odwrotnie.', 'Geometria analityczna', ARRAY['Równanie prostej w postaci kierunkowej'], 20, 3, ARRAY['Uczeń zna i stosuje równanie prostej w postaci ogólnej Ax + By + C = 0.', 'Uczeń przekształca równanie z postaci ogólnej do kierunkowej i odwrotnie.', 'Uczeń rozpoznaje proste równoległe i prostopadłe na podstawie równań.']),

('Odległość punktu od prostej', 'geometry', 'intermediate', 10, 'III.4.2', 'Uczeń oblicza odległość punktu od prostej w układzie współrzędnych, korzystając ze wzoru analitycznego.', 'Geometria analityczna', ARRAY['Równanie prostej w postaci ogólnej'], 25, 3, ARRAY['Uczeń zna wzór na odległość punktu P(x0,y0) od prostej Ax+By+C=0: d = |Ax0+By0+C| / √(A^2+B^2).', 'Uczeń stosuje wzór do obliczania odległości punktu od danej prostej.', 'Uczeń interpretuje geometrycznie otrzymany wynik.']),

('Równanie okręgu w układzie współrzędnych', 'geometry', 'basic', 9, 'III.4.3', 'Uczeń zapisuje równanie okręgu o środku w punkcie (a, b) i promieniu r w postaci (x - a)^2 + (y - b)^2 = r^2.', 'Geometria analityczna', ARRAY['Podstawy układu współrzędnych'], 20, 2, ARRAY['Uczeń zna wzór na równanie okręgu o danym środku i promieniu.', 'Uczeń rozpoznaje równanie okręgu i potrafi wskazać jego środek i promień.', 'Uczeń rysuje okrąg w układzie współrzędnych na podstawie równania.']),

('Wektory - dodawanie i odejmowanie', 'geometry', 'basic', 9, 'III.4.4', 'Uczeń wykonuje działania na wektorach w układzie współrzędnych: dodawanie, odejmowanie, mnożenie przez liczbę.', 'Geometria analityczna - wektory', ARRAY['Podstawy układu współrzędnych'], 20, 2, ARRAY['Uczeń dodaje i odejmuje wektory, stosując regułę równoległoboku i/lub rachunek współrzędnych.', 'Uczeń mnoży wektor przez liczbę i interpretuje wynik geometrycznie.', 'Uczeń stosuje działania na wektorach w prostych zadaniach geometrycznych.']),

('Iloczyn skalarny wektorów', 'geometry', 'intermediate', 10, 'III.4.4', 'Uczeń oblicza iloczyn skalarny wektorów i interpretuje go geometrycznie jako miarę kąta między wektorami.', 'Geometria analityczna - wektory', ARRAY['Wektory - dodawanie i odejmowanie'], 25, 3, ARRAY['Uczeń zna wzór na iloczyn skalarny: u·v = |u||v|cosα oraz u·v = x1x2 + y1y2.', 'Uczeń oblicza iloczyn skalarny wektorów w zadaniach liczbowych.', 'Uczeń wykorzystuje iloczyn skalarny do wyznaczania kąta między wektorami i sprawdzania prostopadłości.']);